baseURL = "https://jugmac00.github.io"
languageCode = "en-us"
title = "Jürgen Gmach"
theme = "PaperMod"

[params]
defaultTheme = "auto"

# Shown on the home page
socialIcons = [
  { name = "email", url = "mailto:juergen.gmach@googlemail.com" },
  { name = "github", url = "https://github.com/jugmac00" },
  { name = "twitter", url = "https://twitter.com/jugmac00" },
  { name = "youtube", url = "https://www.youtube.com/channel/UC_Jpu61dpHkxiCbTNQkKYrg" },
  { name = "python", url = "https://discuss.python.org/u/jugmac00/summary" },
  { name = "stackoverflow", url = "https://stackoverflow.com/users/672833/j-g"},
  { name = "linkedin", url="https://www.linkedin.com/in/j%C3%BCrgen-gmach-b24363226/"},
]

# Configure the home page
[params.profileMode]
enabled = true
title = "Hi, I'm Jürgen."
subtitle = "Say hello to me at various places on the internet."


# configure navigation
[[menu.main]]
weight = 1
identifier = "about"
name = "about"
title = "about"
url = "/about/"

[[menu.main]]
weight = 2
identifier = "blog"
name = "blog"
title = "blog"
url = "/blog/"

[[menu.main]]
weight = 2
identifier = "til"
name = "today-i-learned"
title = "til"
url = "/til/"

[[menu.main]]
weight = 3
identifier = "talks"
name = "talks"
title = "talks"
url = "/talks/"

[[menu.main]]
weight = 4
identifier = "hiring"
name = "hiring"
title = "hiring"
url = "/hiring/"


[taxonomies]
  tag = "tags"
